export const QUERY_KEYS = {
  GET_ME: "get-me",
  GET_USERS: "get-users",
  GET_CHAT_AGENTS: "get-chat-agents",
  GET_AVAILABLE_CHAT_AGENTS: "get-available-chat-agents",
  GET_CHAT_AGENT: "get-chat-agent",
  GET_CHAT_AGENT_OPTIONS: "get-chat-agent-options",
  GET_KNOWLEDGE_SOURCES: "get-knowledge-sources",
  GET_KNOWLEDGE_SOURCE: "get-knowledge-source",
  GET_KNOWLEDGE_SUMMARY: "get-knowledge-summary",
  GET_WIDGET_INBOX_THREADS: "get-widget-inbox-threads",
  GET_WIDGET_INBOX_THREAD: "get-widget-inbox-thread",
  GET_WIDGET_INBOX_STATS: "get-widget-inbox-stats",
  GET_FEEDBACK_PATTERNS: "get-feedback-patterns",
  GET_AI_USAGE: "get-ai-usage",
  GET_WHATSAPP_STATUS: "get-whatsapp-status",
  GET_WHATSAPP_CONTACT: "get-whatsapp-contact",
  GET_WHATSAPP_CONTACTS: "get-whatsapp-contacts",
  GET_WHATSAPP_ANALYTICS: "get-whatsapp-analytics",
  GET_WHATSAPP_TEMPLATES: "get-whatsapp-templates",
  GET_WHATSAPP_STYLE_NOTES: "get-whatsapp-style-notes",
  GET_WHATSAPP_FOLLOWUP_RULES: "get-whatsapp-followup-rules",
  GET_WHATSAPP_FOLLOWUP_STAGES: "get-whatsapp-followup-stages",
  GET_WHATSAPP_FOLLOWUP_UPCOMING: "get-whatsapp-followup-upcoming",
  GET_WHATSAPP_FOLLOWUP_STATS: "get-whatsapp-followup-stats",
} as const;
